# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('about', '\u043e\u0431\u043e \u043c\u043d\u0435'), ('documents', '\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b'), ('group', '\u0433\u0440\u0443\u043f\u043f\u0430'), ('parents', '\u0434\u043b\u044f \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u0439'), ('methodic', '\u043c\u043e\u0438 \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438'), ('news', '\u043d\u043e\u0432\u043e\u0441\u0442\u0438'), ('gallery', '\u0444\u043e\u0442\u043e\u0433\u0430\u043b\u0435\u0440\u0435\u044f'), ('contacts', '\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], default='about', max_length=20, verbose_name='\u043a\u043e\u0440\u043d\u0435\u0432\u043e\u0435 \u043c\u0435\u043d\u044e'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043c\u0435\u043d\u044e(\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0432 \u043d\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u0438)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.CharField(choices=[('null_page', '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0435\u0449\u0435 \u043d\u0435 \u0441\u043e\u0437\u0434\u0430\u043d\u0430'), ('special', '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0431\u0435\u0437 \u0432\u044b\u0431\u043e\u0440\u0430 \u0442\u0438\u043f\u0430 \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430'), ('documents', '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0441 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430\u043c\u0438'), ('editor', '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0441 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435\u043c \u0442\u0435\u043a\u0441\u0442\u0430')], default='null_page', max_length=20, verbose_name='\u0442\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u043f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043c\u0435\u043d\u044e(\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0430\u0445)'),
        ),
    ]
