# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190324_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430\u0441\u0442\u0440\u043e\u0435\u043a')),
                ('email_host', models.CharField(default=b'smtp.gmail.com', max_length=50, verbose_name='\u0445\u043e\u0441\u0442')),
                ('email_host_port', models.IntegerField(default=587, verbose_name='\u043f\u043e\u0440\u0442')),
                ('email_use_tsl', models.BooleanField(default=True, verbose_name='\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0437\u0430\u0449\u0438\u0449\u0435\u043d\u043e\u0435 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435 TSL')),
                ('email_host_user', models.CharField(max_length=50, verbose_name='\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430')),
                ('email_host_password', models.CharField(max_length=50, verbose_name='\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043d\u044b\u0439 \u043f\u0430\u0440\u043e\u043b\u044c')),
            ],
            options={
                'db_table': 'mailsets',
                'verbose_name': '\u0428\u043b\u044e\u0437 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u043f\u043e\u0447\u0442\u044b',
                'verbose_name_plural': '\u0428\u043b\u044e\u0437\u044b \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u043f\u043e\u0447\u0442\u044b',
            },
        ),
    ]
