# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_mailset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailset',
            name='email_use_tsl',
        ),
        migrations.AddField(
            model_name='mailset',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0437\u0430\u0449\u0438\u0449\u0435\u043d\u043e\u0435 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435 TLS'),
        ),
    ]
