# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190326_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailset',
            name='default',
            field=models.BooleanField(default=False, verbose_name='\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u044d\u0442\u0438 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438 \u043f\u043e\u0447\u0442\u044b'),
        ),
    ]
