# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_mailset_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailset',
            name='email_use_ssl',
            field=models.BooleanField(default=True, verbose_name='\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0448\u0438\u0444\u0440\u043e\u0432\u0430\u043d\u0438\u0435 SSL'),
        ),
    ]
