# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 04:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('description', models.CharField(choices=[(b'grateful', b'\xd0\xb1\xd0\xbb\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xb4\xd0\xb0\xd1\x80\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c'), (b'letter', b'\xd0\xb3\xd1\x80\xd0\xb0\xd0\xbc\xd0\xbe\xd1\x82\xd0\xb0'), (b'diplom', b'\xd0\xb4\xd0\xb8\xd0\xbf\xd0\xbb\xd0\xbe\xd0\xbc'), (b'qualification', b'\xd1\x83\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'), (b'certificate', b'\xd1\x81\xd0\xb5\xd1\x80\xd1\x82\xd0\xb8\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0\xd1\x82')], default=1, max_length=50, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf')),
                ('date', models.DateField(verbose_name=b'\xd0\xb4\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('photo', models.ImageField(upload_to=b'awards/', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435/\u0441\u043a\u0430\u043d')),
            ],
            options={
                'db_table': 'awards',
                'verbose_name': '\u043d\u0430\u0433\u0440\u0430\u0436\u0434\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u043d\u0430\u0433\u0440\u0430\u0436\u0434\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xd0\xbd\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xba\xd0\xbe\xd0\xbd\xd1\x82\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0')),
                ('type', models.CharField(choices=[(b'text', b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82'), (b'pic', b'\xd0\x98\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'), (b'VIDEO', b'\xd0\x92\xd0\xb8\xd0\xb4\xd0\xb5\xd0\xbe'), (b'doc', b'\xd0\x94\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82')], default=b'pic', max_length=20, verbose_name='\u0442\u0438\u043f \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430')),
                ('file', models.ImageField(blank=True, default=b'content/image.jpg', null=True, upload_to=b'content/', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('text', ckeditor.fields.RichTextField(verbose_name='\u0431\u043b\u043e\u043a \u0442\u0435\u043a\u0441\u0442\u0430')),
            ],
            options={
                'db_table': 'content',
                'verbose_name': '\u0437\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u043c\u044b\u0439 \u043a\u043e\u043d\u0442\u0435\u043d\u0442',
                'verbose_name_plural': '\u0437\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u043c\u044b\u0439 \u043a\u043e\u043d\u0442\u0435\u043d\u0442',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xba\xd1\x83\xd1\x80\xd1\x81\xd0\xb0 \xd0\xbf\xd0\xbe\xd0\xb2\xd1\x8b\xd1\x88\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xba\xd0\xb2\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8')),
                ('begin_date', models.DateField(verbose_name=b'\xd0\xb4\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xb0 \xd0\xba\xd1\x83\xd1\x80\xd1\x81\xd0\xb0')),
                ('finish_date', models.DateField(verbose_name=b'\xd0\xb4\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb7\xd0\xb0\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xba\xd1\x83\xd1\x80\xd1\x81\xd0\xb0')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name=b'\xd0\xb4\xd0\xbb\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xba\xd1\x83\xd1\x80\xd1\x81\xd0\xb0(\xd1\x87\xd0\xb0\xd1\x81\xd0\xbe\xd0\xb2)')),
                ('place', models.CharField(max_length=100, verbose_name=b'\xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xba\xd1\x83\xd1\x80\xd1\x81\xd0\xb0')),
            ],
            options={
                'db_table': 'courses',
                'verbose_name': '\u043a\u0443\u0440\u0441 \u043f\u043e\u0432\u044b\u0448\u0435\u043d\u0438\u044f \u043a\u0432\u0430\u043b\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u043a\u0443\u0440\u0441\u044b \u043f\u043e\u0432\u044b\u0448\u0435\u043d\u0438\u044f \u043a\u0432\u0430\u043b\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438',
            },
        ),
    ]
