# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(verbose_name='\u0434\u0430\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(choices=[('grateful', '\u0431\u043b\u0430\u0433\u043e\u0434\u0430\u0440\u043d\u043e\u0441\u0442\u044c'), ('letter', '\u0433\u0440\u0430\u043c\u043e\u0442\u0430'), ('diplom', '\u0434\u0438\u043f\u043b\u043e\u043c'), ('qualification', '\u0443\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0435\u043d\u0438\u0435'), ('certificate', '\u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442')], default=1, max_length=50, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=150, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('text', '\u0422\u0435\u043a\u0441\u0442'), ('pic', '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'), ('VIDEO', '\u0412\u0438\u0434\u0435\u043e'), ('doc', '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442')], default='pic', max_length=20, verbose_name='\u0442\u0438\u043f \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='course',
            name='begin_date',
            field=models.DateField(verbose_name='\u0434\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u043a\u0443\u0440\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0434\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u043a\u0443\u0440\u0441\u0430(\u0447\u0430\u0441\u043e\u0432)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='finish_date',
            field=models.DateField(verbose_name='\u0434\u0430\u0442\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u043a\u0443\u0440\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0443\u0440\u0441\u0430 \u043f\u043e\u0432\u044b\u0448\u0435\u043d\u0438\u044f \u043a\u0432\u0430\u043b\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='course',
            name='place',
            field=models.CharField(max_length=100, verbose_name='\u043c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u043a\u0443\u0440\u0441\u0430'),
        ),
    ]
